### ISSUE TITLE
友達登録を一方向のものにする

### ISSUE THREAD

**Issue by tkp0331** [ktanonymous/sketch#29]
AがBに友達申請をした時，A->Bの関係とB->Aの関係の両方が形成されてしまう。  
これをA->Bの関係**のみ**を登録するように改修する。

**Comment by tkp0331** [comment]
@ktanonymous 
仕事で割り当てられたissueの中に地味に混じって表示されていて邪魔なので削除してくれ笑  
（権限的に俺には削除できない）

**Comment by ktanonymous** [comment]
close します
