### ISSUE TITLE
友達登録の可否を確認する

### ISSUE THREAD

**Issue by tkp0331** [ktanonymous/sketch#30]
2021年8月31日現在の実装では，友達申請を行うだけで友達になれてしまう。  
申請された側で許可/不許可を選択出来るようにする。

**Comment by tkp0331** [comment]
@ktanonymous 
仕事で割り当てられたissueの中に地味に混じって表示されていて邪魔なので削除してくれ笑  
（権限的に俺には削除できない）

**Comment by ktanonymous** [comment]
close します
